### ISSUE TITLE
string.h in dlib

### ISSUE THREAD

**Issue by ofZach** [HalfdanJ/ofxFaceTracker2#30]
I don't know how to articulate this issue well but I'm trying to get dlib / ofxFaceTracker2 working on android (using https://medium.com/@ire_alva/getting-started-with-openframeworks-on-android-5202b92f6582) and I'm hitting an issue where stdlib seems to be getting messed up 

<img width="864" alt="screen shot 2017-12-05 at 4 27 04 pm" src="https://user-images.githubusercontent.com/142897/33631651-2cf64ae6-d9d9-11e7-889d-16fece5528ae.png">

after poking around for a bit it seems that it's probably about this issue: 

https://github.com/torognes/vsearch/issues/91

where the including of "string.h" messes up things.    dlib has a string.h file :( 

I don't know if there's a better change then renaming the file, which I may try first...   Just thought I'd mention it while I work on a fix.

**Comment by ofZach** [comment]
assert.h also seems to be an issue

**Comment by ofZach** [comment]
I'm sure this is something simple like include order, but my solution was just to rename string.h and assert.h to xstring.h and xassert.h and change all includes inside dlib

**Comment by HalfdanJ** [comment]
I assume its because I need to update the build for later version of ndk. This was build using NDK12 i believe. yay for NDK versions :)

**Comment by ofZach** [comment]
thanks ! I feel like this may have to do with how the addon is included in android studio -- it's a little hard for me to read how gradle is handling addons but I'll poke around..

I noticed the following text in the Dlib installation instructions:

`Again, note that you should not add the dlib folder itself to your compiler's include path. Doing so will cause the build to fail because of name collisions (e.g. dlib/string.h with string.h from the standard library). Instead you should add the folder that contains the dlib folder to your include search path and then use include statements of the form #include <dlib/queue.h>. This will ensure that everything builds correctly.`

http://dlib.net/compile.html

**Comment by HalfdanJ** [comment]
Should have been fixed with latest pr from dan

**Comment by zkg** [comment]
I can confirm that this issue is still present, at least working from android-studio. Had to rename files the good old way, for lack of a better option.

**Comment by llitfkitfk** [comment]
https://github.com/googlecreativelab/giantemoji/issues/22
